### ISSUE TITLE
Use of System.exit() on parser errors in CSSParser

### ISSUE THREAD

**Issue by void256** [phil-brown/jCSS-Parser#2]
Hi Phil,

thanks for the jCSS-Parser! It works very well and has been very easy to use! :smile:

However, there is one strange thing. On parser errors (in my case I had a regular "//" comment that is not allowed in CSS somewhere) the `handler.handleError()` is correctly called but then immediatly after that a `System.exit(0)` is performed.

I think this is a bit harsh :wink:

Is there a special reason for that or can this be changed into a `throw new IOException()` or something similar instead?

I've found it on three spots in the CSSParser class here:

https://github.com/phil-brown/jCSS-Parser/blob/master/CSS%20Parser/src/self/philbrown/cssparser/CSSParser.java#L83
https://github.com/phil-brown/jCSS-Parser/blob/master/CSS%20Parser/src/self/philbrown/cssparser/CSSParser.java#L304
https://github.com/phil-brown/jCSS-Parser/blob/master/CSS%20Parser/src/self/philbrown/cssparser/CSSParser.java#L460

I can provide a pull request if your time is limited but just wanted to ask if this has to be that way - although I can't think of a reason, right now.

void

**Comment by phil-brown** [comment]
@void256 great suggestion and thanks for the positive feedback! I'll get a fix in very soon.

**Comment by phil-brown** [comment]
@void256 I have not touched this code in quite some time, but the reasoning that the exception is handled as-is, is that a syntax error might cause the rest of the parser to work incorrectly. The `//` syntax is - from what I have read - **not** the correct way to specify a comment. According to [w3schools.com](http://www.w3schools.com/css/css_syntax.asp), `/*comment*/` is the correct syntax. It does seem harsh to call `System.exit()` though, considering that it would cause applications (such as integration in Android, etc) to have issues, so I definitely agree with that part. So to approach the issue, I plan to add a custom _ParseError_ that will stop all parsing, but not call `System.exit()`. What are your thoughts? Does using the `/*` syntax work for the issue described above? If not, the correct place to add code to include this sort of comments would be line 262 of Scanner.java. I'll add an improved exception handling later today, and thanks for pointing this out! 

Also, I am really excited that someone is getting some use out of this, and that it is working well :smile: Please continue to report any issues you find. I will be happy to help.

Best,
Phil

**Comment by void256** [comment]
It's not necessary to add support for `//` comments since the correct way in CSS is to use `/* ... */`. That is ok! :smile:

I think it's okay to stop parsing in that case. Why not simply throw an IOException to notify the caller of the error? The caller of the parse() method already has to take care of that Exception and in case of a SyntaxError he's kinda doomed anyway :wink:

And yes, I like your project because it does what it says, it simply parses the CSS and that's it. Most other projects I've checked are created with HTML/CSS processing in mind so they all do more than what I needed.

So far, I did not have other issues :smile: The only thing I'd eventually like to see would be the packaging of your lib as a Maven dependeny to make it available in the central Maven Repository. It would make re-using your lib for Maven users easier! But that is a minor thing really.

**Comment by phil-brown** [comment]
@void256 I just made some minor changes, and created a new release, available [here](https://github.com/phil-brown/jCSS-Parser/releases/tag/0.0.5). This now throws a [ParseException](http://docs.oracle.com/javase/7/docs/api/java/text/ParseException.html) if the parsing fails, but no longer calls `System.exit(0)`. Again - great find! I'm currently looking into how to add Maven support, I definitely would like to add that option in the near future.

Please let me know if this issue is resolved.

**Comment by void256** [comment]
Will try it as soon as I can. Thanks already!

**Comment by void256** [comment]
Works as expected! Thanks for the quick fix! :smile:
